# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coso',
            fields=[
                ('id_coso', models.BigIntegerField(db_column='IDCOSO', primary_key=True, serialize=False)),
                ('descrizione_coso', models.CharField(db_column='DECOSO', max_length=255)),
            ],
        ),
    ]
