# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_coso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributoCoso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_attributo', models.CharField(db_column='CODATTR', max_length=20)),
                ('valore_attributo', models.CharField(db_column='VALATTR', max_length=255)),
                ('id_coso', models.ForeignKey(db_column='IDCOSO', on_delete=django.db.models.deletion.CASCADE, to='polls.Coso')),
            ],
        ),
    ]
