# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_attributocoso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributocoso',
            name='id_coso',
            field=models.ForeignKey(db_column='IDCOSO', on_delete=django.db.models.deletion.PROTECT, to='polls.Coso'),
        ),
    ]
